### ISSUE TITLE
V2 - Page Container

### ISSUE THREAD

**Issue by Flavyoo** [blitz-js/blitzjs.com#261]
Create the Page Container component.

The PageContainer is a simple component that we wrap contents of pages with. It's main responsibility is to have a bounding width to prevent contents pages from extending beyond certain screen sizes or causing content in the pages to stretch too much.

Checkout the [Figma design](https://www.figma.com/file/KxLHA7cVPEy1fNE2bD8wWv/Blitz?node-id=1147%3A0). Take note of how there is a limit on the width of the page with margin to the left and right.

- [ ] Bounding width based on the figma design.

- [ ] Proper margin on left and right.

- [ ] Centered relative to the Layout component. #256

**Comment by abuuzayr** [comment]
Since the entire site (home, docs, etc.) are wrapped with the same layout (header, footer, banner) - unlike the tailwind site - I will be extracting the current index page and wrap a layout around it so other pages can use it as well. 

I'll work on this if nobody is on it yet.

**Comment by Flavyoo** [comment]
@abuuzayr Thanks for picking this up! Please add me to the review.

**Comment by flybayer** [comment]
@abuuzayr actually I don't think a layout component will work to add the top and bottom nav because the homepage is so complex it has to pull in the individual components too.

The docs pages all match, but they already have a shared layout. And we currently don't have any other pages, so I'll close this for now.
